### ISSUE TITLE
[Documentation] Could the main README mention which operating systems are supported?

### ISSUE THREAD

**Issue by rubyFeedback** [mvz/gir_ffi-gtk#103]
First, I got confused yesterday. I think the github repository "gir_ffi" confused me and I wondered
about the examples, but now I am going through:

https://github.com/mvz/gir_ffi-gtk/tree/master/examples

And these work! \o/ So perhaps I actually meant to go to gir_ffi-gtk rather than gir_ffi (they 
kind of looked similar if you look only briefly at the monitor ... sometimes I find the same
project again at a later google search without realising the difference).

If you have several projects/gems, perhaps it can be mentioned or cross-referenced more clearly
or easily in the README about the different projects - some people, such as me, get easily
confused. I have like 30 tabs open right now, multitask a lot and it's confusing my brain ... :D

Anyway. For this issue here, would it be possible to mention in the README which operating
systems are supported? Evidently Linux, I am using that right now, so that works fine, but I'd like
to know if OSX/Apple and Windows/Microsoft would also be supported, if gtk/gdk/gobject-introspection
is available. That way people can quickly see whether the gir-bindings here could work.

By the way, I think many people don't know about the project. Not sure why, I think I found
it only by accident years ago, and then didn't pay attention. The recent gtk4 gem for 
ruby-gtk kind of made me interested again so I googled, and found other projects, 
again, this one, but also Natalie (if you have not heard about it, the author is also using
ruby; it looks interesting, I asked for GUI examples recently: https://natalie-lang.org/ )

PS: After I have worked through the examples I will consider seeing whether I can support
gir_ffi-gtk via my gtk_paradise gem. That gem is a bit messy 
https://rubygems.org/gems/gtk_paradise but a few days ago I tested the same .rb file for
both ruby-gtk3 and ruby-gtk4 and that actually works. So my hope or idea is that I can
use the same code base, sort of, and support all the different gtk-variants / dialects
including gtk2. But right now it's a bit of a mess and I don't want to make any promise -
for now I just focus on ruby-gtk3 mostly, as I can write more code in it and that works
fine; with ruby-gtk4 aka the gtk4 gem I ran into a few problems, including the changed
signal event handling. Not yet sure what to do about that, in ruby-gtk3 it seems much 
easier.

**Comment by mvz** [comment]
Hi @rubyFeedback please let me know if these sections give you the information you seek: https://github.com/mvz/gir_ffi#requirements and https://github.com/mvz/gir_ffi#overrides.

**Comment by mvz** [comment]
(Natalie looks interesting by the way)

**Comment by mvz** [comment]
I suppose I should mention the status of Windows and OSX support in each of the READMEs, not just the one for `gir_ffi` :thinking:.

**Comment by mvz** [comment]
Fix in master for this and other GirFFI gems: https://github.com/mvz/gir_ffi-gtk#requirements
