### ISSUE TITLE
GTK_STOCK_* unavailable

### ISSUE THREAD

**Issue by kugel-** [mvz/gir_ffi-gtk#20]
I can't seem to find the definitions. Am I looking at the wrong place (I'm expecting Gtk::STOCK_EXECUTE or something like this)

**Comment by mvz** [comment]
This works for me:

```ruby
require 'gir_ffi-gtk3'
puts Gtk::STOCK_EXECUTE
```

**Comment by mvz** [comment]
Note that these constants are lazy-loaded.

**Comment by kugel-** [comment]
I can confirm it works. Sorry for the noise.

**Comment by mvz** [comment]
NP
