### ISSUE TITLE
Background window

### ISSUE THREAD

**Issue by symbolunderscore** [mvz/gir_ffi-gtk#21]
Hello
How i can change background color of my window ?

**Comment by mvz** [comment]
That's a bit tricky and really not specific to GirFFI. In Gtk+, it seems you're supposed to use CSS for this: https://developer.gnome.org/gtk3/stable/GtkStyleContext.html#id-1.5.4.10.8

**Comment by mvz** [comment]
There's some more info on how Gtk+ uses CSS here: https://developer.gnome.org/gtk3/stable/chap-css-overview.html

**Comment by mvz** [comment]
Closing this as this is not a bug in GirFFI-Gtk.
